name = "veneth-portfolio"
compatibility_date = "2024-01-01"
compatibility_flags = [" Durable Object UNRESTRICTED_LOAD_BALANCER"]

pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "veneth-contacts"
database_id = "2ad99ae7-3e5c-414c-b32e-06b1e3d8b52a"

[[workers]]
binding = "DB"
script = "veneth-contact-api"
