name = "veneth-studio"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "veneth-studio"
database_id = "bdaa8030-de52-4a75-b934-4a3d2feaf2ae"

[vars]
FROM_EMAIL = "noreply@veneth.studio"
